import type { PhotoDetail, PhotoFile, PhotoSummary } from "@/lib/types";

export function summary(over: Partial<PhotoSummary> = {}): PhotoSummary {
  return {
    id: "11111111-1111-1111-1111-111111111111",
    base_filename: "DSC_0042",
    media_type: "still",
    capture_time: "2026-09-30T15:04:05Z",
    imported_at: "2026-09-30T15:04:09Z",
    camera: "Nikon Z6III",
    lens_model: "NIKKOR Z 50mm f/1.4",
    focal_length: 50,
    aperture: 1.4,
    shutter_speed: 0.002,
    iso: 400,
    exposure_compensation: -0.3333,
    rating: 0,
    flag: "none",
    rejected: false,
    picked: false,
    favorite: false,
    needs_edit: false,
    exported: false,
    has_jpeg: true,
    has_raw: true,
    has_video: false,
    processing_status: "ready",
    scene: null,
    burst_group_id: null,
    burst_index: null,
    burst_size: null,
    thumb_url: "/api/v1/photos/1111/thumbnail?size=512",
    thumb_width: 512,
    thumb_height: 341,
    sharpness_score: 62,
    exposure_label: "good",
    face_count: 0,
    ...over,
  };
}

export function file(over: Partial<PhotoFile> = {}): PhotoFile {
  return {
    id: "f1",
    file_type: "raw",
    filename: "DSC_0042.NEF",
    extension: "nef",
    mime_type: "image/x-nikon-nef",
    file_size: 52_428_800,
    checksum: "abc",
    modification_time: "2026-09-30T15:04:08Z",
    width: 6048,
    height: 4032,
    exists: true,
    is_duplicate: false,
    container_path: "/photos/raw/2026/09/30/DSC_0042.NEF",
    nas_path: "/mnt/mainpool/photos/z6iii/raw/2026/09/30/DSC_0042.NEF",
    smb_path: "\\\\truenas\\photos\\z6iii\\raw\\2026\\09\\30\\DSC_0042.NEF",
    relative_path: "raw/2026/09/30/DSC_0042.NEF",
    download_url: "/api/v1/files/f1/download",
    ...over,
  };
}

export function detail(over: Partial<PhotoDetail> = {}): PhotoDetail {
  return {
    ...summary(),
    camera_make: "NIKON CORPORATION",
    camera_model: "NIKON Z6_3",
    camera_serial: "6000123",
    shutter_count: 2567,
    firmware: "1.10",
    capture_tz_offset: "-05:00",
    focal_length_35mm: 50,
    exposure_program: "Aperture-priority AE",
    metering_mode: "Multi-segment",
    white_balance: "Auto",
    flash: "No Flash",
    focus_mode: "AF-C",
    af_area_mode: "Auto",
    picture_control: "Standard",
    image_quality: "RAW + Fine",
    image_width: 6048,
    image_height: 4032,
    orientation: 1,
    color_space: "sRGB",
    duration_seconds: null,
    gps_latitude: null,
    gps_longitude: null,
    gps_altitude: null,
    extra: { vibration_reduction: "On" },
    notes: null,
    processing_error: null,
    preview_url: "/api/v1/photos/1111/preview",
    preview_width: 2560,
    preview_height: 1707,
    files: [file(), file({ id: "f2", file_type: "jpeg", filename: "DSC_0042.JPG", smb_path: null })],
    analysis: null,
    critique: null,
    critique_history: 0,
    tags: [],
    albums: [],
    burst: null,
    immich_asset_id: null,
    immich_url: null,
    immich_enabled: false,
    prev_id: null,
    next_id: null,
    ...over,
  };
}
