"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 02:45:30.830681
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burst_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_key', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('cover_photo_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_burst_groups'))
    )
    op.create_index('ix_burst_groups_start_time', 'burst_groups', ['start_time'], unique=False)
    op.create_table('ingest_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_model', sa.String(length=64), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('jpeg_count', sa.Integer(), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_sessions'))
    )
    op.create_index('ix_ingest_sessions_last_activity', 'ingest_sessions', ['last_activity_at'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('base_filename', sa.String(length=255), nullable=False),
    sa.Column('base_key', sa.String(length=255), nullable=False),
    sa.Column('capture_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_tz_offset', sa.String(length=8), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_make', sa.String(length=64), nullable=True),
    sa.Column('camera_model', sa.String(length=64), nullable=True),
    sa.Column('camera_serial', sa.String(length=64), nullable=True),
    sa.Column('shutter_count', sa.Integer(), nullable=True),
    sa.Column('firmware', sa.String(length=32), nullable=True),
    sa.Column('lens_model', sa.String(length=128), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('focal_length_35mm', sa.Float(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.Float(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('exposure_compensation', sa.Float(), nullable=True),
    sa.Column('exposure_program', sa.String(length=64), nullable=True),
    sa.Column('metering_mode', sa.String(length=64), nullable=True),
    sa.Column('white_balance', sa.String(length=64), nullable=True),
    sa.Column('flash', sa.String(length=128), nullable=True),
    sa.Column('focus_mode', sa.String(length=64), nullable=True),
    sa.Column('af_area_mode', sa.String(length=64), nullable=True),
    sa.Column('picture_control', sa.String(length=64), nullable=True),
    sa.Column('image_quality', sa.String(length=64), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.SmallInteger(), nullable=True),
    sa.Column('color_space', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_altitude', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('flag', sa.String(length=16), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('needs_edit', sa.Boolean(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('has_jpeg', sa.Boolean(), nullable=False),
    sa.Column('has_raw', sa.Boolean(), nullable=False),
    sa.Column('has_video', sa.Boolean(), nullable=False),
    sa.Column('scene', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('immich_asset_id', sa.String(length=64), nullable=True),
    sa.Column('burst_group_id', sa.Uuid(), nullable=True),
    sa.Column('burst_index', sa.Integer(), nullable=True),
    sa.Column('ingest_session_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['burst_group_id'], ['burst_groups.id'], name=op.f('fk_photos_burst_group_id_burst_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingest_session_id'], ['ingest_sessions.id'], name=op.f('fk_photos_ingest_session_id_ingest_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index('ix_photos_base_key', 'photos', ['base_key'], unique=False)
    op.create_index('ix_photos_burst_group_id', 'photos', ['burst_group_id'], unique=False)
    op.create_index('ix_photos_camera_model', 'photos', ['camera_model'], unique=False)
    op.create_index('ix_photos_camera_shutter', 'photos', ['camera_serial', 'shutter_count'], unique=False)
    op.create_index('ix_photos_capture_time', 'photos', ['capture_time'], unique=False)
    op.create_index('ix_photos_flag', 'photos', ['flag'], unique=False)
    op.create_index('ix_photos_imported_at', 'photos', ['imported_at'], unique=False)
    op.create_index('ix_photos_ingest_session_id', 'photos', ['ingest_session_id'], unique=False)
    op.create_index('ix_photos_lens_model', 'photos', ['lens_model'], unique=False)
    op.create_index('ix_photos_rating', 'photos', ['rating'], unique=False)
    op.create_table('ai_critiques',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scene', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('composition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('technical', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('suggestions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('aesthetic_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_ai_critiques_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_critiques'))
    )
    op.create_index('ix_ai_critiques_photo_created', 'ai_critiques', ['photo_id', 'created_at'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_photo_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photos.id'], name=op.f('fk_albums_cover_photo_id_photos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('queue', sa.String(length=32), nullable=False),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_jobs_photo_id_photos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_kind', 'jobs', ['kind'], unique=False)
    op.create_index('ix_jobs_photo_id', 'jobs', ['photo_id'], unique=False)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('photo_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('absolute_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('modification_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('exif', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['photo_files.id'], name=op.f('fk_photo_files_duplicate_of_id_photo_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_files_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_files')),
    sa.UniqueConstraint('absolute_path', name=op.f('uq_photo_files_absolute_path'))
    )
    op.create_index('ix_photo_files_checksum', 'photo_files', ['checksum'], unique=False)
    op.create_index('ix_photo_files_file_type', 'photo_files', ['file_type'], unique=False)
    op.create_index('ix_photo_files_photo_id', 'photo_files', ['photo_id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_tags_photo_id_photos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_photo_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'tag_id', name=op.f('pk_photo_tags'))
    )
    op.create_index('ix_photo_tags_tag_id', 'photo_tags', ['tag_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_system_events_photo_id_photos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_system_events_category', 'system_events', ['category'], unique=False)
    op.create_index('ix_system_events_created_at', 'system_events', ['created_at'], unique=False)
    op.create_table('technical_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('sharpness_score', sa.Float(), nullable=True),
    sa.Column('sharpness_label', sa.String(length=32), nullable=True),
    sa.Column('sharpness_global', sa.Float(), nullable=True),
    sa.Column('sharpness_peak', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('is_blurry', sa.Boolean(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('saturation', sa.Float(), nullable=True),
    sa.Column('dynamic_range_ev', sa.Float(), nullable=True),
    sa.Column('highlight_clipping_percent', sa.Float(), nullable=True),
    sa.Column('shadow_clipping_percent', sa.Float(), nullable=True),
    sa.Column('exposure_label', sa.String(length=32), nullable=True),
    sa.Column('exposure_assessment', sa.Text(), nullable=True),
    sa.Column('histogram', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dominant_colors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('eye_count', sa.Integer(), nullable=True),
    sa.Column('faces', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('subject_detected', sa.Boolean(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('analyzed_width', sa.Integer(), nullable=True),
    sa.Column('analyzed_height', sa.Integer(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_technical_analyses_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_analyses')),
    sa.UniqueConstraint('photo_id', name=op.f('uq_technical_analyses_photo_id'))
    )
    op.create_table('photo_albums',
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_photo_albums_album_id_albums'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_albums_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'photo_id', name=op.f('pk_photo_albums'))
    )
    op.create_index('ix_photo_albums_photo_id', 'photo_albums', ['photo_id'], unique=False)
    op.create_table('renditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('source_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_renditions_photo_id_photos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['photo_files.id'], name=op.f('fk_renditions_source_file_id_photo_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renditions')),
    sa.UniqueConstraint('photo_id', 'kind', name='uq_renditions_photo_kind')
    )
    # ### end Alembic commands ###

    # burst_groups <-> photos is circular, so this FK is added after both exist.
    op.create_foreign_key(
        op.f('fk_burst_groups_cover_photo_id_photos'), 'burst_groups', 'photos',
        ['cover_photo_id'], ['id'], ondelete='SET NULL',
    )
    if op.get_bind().dialect.name == 'postgresql':
        # Must match the expression used in app/services/search.py exactly.
        op.execute(
            "CREATE INDEX ix_photos_search_fts ON photos "
            "USING gin (to_tsvector('simple', search_text))"
        )
        op.execute("CREATE INDEX ix_photos_capture_time_desc ON photos (capture_time DESC NULLS LAST, id)")


def downgrade() -> None:
    op.drop_constraint(op.f('fk_burst_groups_cover_photo_id_photos'), 'burst_groups', type_='foreignkey')
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP INDEX IF EXISTS ix_photos_search_fts")
        op.execute("DROP INDEX IF EXISTS ix_photos_capture_time_desc")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renditions')
    op.drop_index('ix_photo_albums_photo_id', table_name='photo_albums')
    op.drop_table('photo_albums')
    op.drop_table('technical_analyses')
    op.drop_index('ix_system_events_created_at', table_name='system_events')
    op.drop_index('ix_system_events_category', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_photo_tags_tag_id', table_name='photo_tags')
    op.drop_table('photo_tags')
    op.drop_index('ix_photo_files_photo_id', table_name='photo_files')
    op.drop_index('ix_photo_files_file_type', table_name='photo_files')
    op.drop_index('ix_photo_files_checksum', table_name='photo_files')
    op.drop_table('photo_files')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_index('ix_jobs_photo_id', table_name='jobs')
    op.drop_index('ix_jobs_kind', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('albums')
    op.drop_index('ix_ai_critiques_photo_created', table_name='ai_critiques')
    op.drop_table('ai_critiques')
    op.drop_index('ix_photos_rating', table_name='photos')
    op.drop_index('ix_photos_lens_model', table_name='photos')
    op.drop_index('ix_photos_ingest_session_id', table_name='photos')
    op.drop_index('ix_photos_imported_at', table_name='photos')
    op.drop_index('ix_photos_flag', table_name='photos')
    op.drop_index('ix_photos_capture_time', table_name='photos')
    op.drop_index('ix_photos_camera_shutter', table_name='photos')
    op.drop_index('ix_photos_camera_model', table_name='photos')
    op.drop_index('ix_photos_burst_group_id', table_name='photos')
    op.drop_index('ix_photos_base_key', table_name='photos')
    op.drop_table('photos')
    op.drop_table('tags')
    op.drop_index('ix_ingest_sessions_last_activity', table_name='ingest_sessions')
    op.drop_table('ingest_sessions')
    op.drop_index('ix_burst_groups_start_time', table_name='burst_groups')
    op.drop_table('burst_groups')
    # ### end Alembic commands ###
